// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: kratos/api/auth/service/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_kratos_api_auth_service_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_auth_service_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_kratos_api_auth_service_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`     // Optional: JWT or session token
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Login success/fail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_kratos_api_auth_service_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_auth_service_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_kratos_api_auth_service_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kratos_api_auth_service_v1_auth_proto protoreflect.FileDescriptor

const file_kratos_api_auth_service_v1_auth_proto_rawDesc = "" +
	"\n" +
	"%kratos/api/auth/service/v1/auth.proto\x12\x0fauth.service.v1\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"U\n" +
	"\n" +
	"LoginReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2m\n" +
	"\vAuthService\x12^\n" +
	"\x05Login\x12\x1d.auth.service.v1.LoginRequest\x1a\x1b.auth.service.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/loginB\x1fZ\x1dkratos/api/auth/service/v1;v1b\x06proto3"

var (
	file_kratos_api_auth_service_v1_auth_proto_rawDescOnce sync.Once
	file_kratos_api_auth_service_v1_auth_proto_rawDescData []byte
)

func file_kratos_api_auth_service_v1_auth_proto_rawDescGZIP() []byte {
	file_kratos_api_auth_service_v1_auth_proto_rawDescOnce.Do(func() {
		file_kratos_api_auth_service_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kratos_api_auth_service_v1_auth_proto_rawDesc), len(file_kratos_api_auth_service_v1_auth_proto_rawDesc)))
	})
	return file_kratos_api_auth_service_v1_auth_proto_rawDescData
}

var file_kratos_api_auth_service_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kratos_api_auth_service_v1_auth_proto_goTypes = []any{
	(*LoginRequest)(nil), // 0: auth.service.v1.LoginRequest
	(*LoginReply)(nil),   // 1: auth.service.v1.LoginReply
}
var file_kratos_api_auth_service_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.service.v1.AuthService.Login:input_type -> auth.service.v1.LoginRequest
	1, // 1: auth.service.v1.AuthService.Login:output_type -> auth.service.v1.LoginReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kratos_api_auth_service_v1_auth_proto_init() }
func file_kratos_api_auth_service_v1_auth_proto_init() {
	if File_kratos_api_auth_service_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kratos_api_auth_service_v1_auth_proto_rawDesc), len(file_kratos_api_auth_service_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kratos_api_auth_service_v1_auth_proto_goTypes,
		DependencyIndexes: file_kratos_api_auth_service_v1_auth_proto_depIdxs,
		MessageInfos:      file_kratos_api_auth_service_v1_auth_proto_msgTypes,
	}.Build()
	File_kratos_api_auth_service_v1_auth_proto = out.File
	file_kratos_api_auth_service_v1_auth_proto_goTypes = nil
	file_kratos_api_auth_service_v1_auth_proto_depIdxs = nil
}
