// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: kratos/api/user/service/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_kratos_api_user_service_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_kratos_api_user_service_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)    
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_kratos_api_user_service_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReply) Reset() {
	*x = UserReply{}
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReply) ProtoMessage() {}

func (x *UserReply) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReply.ProtoReflect.Descriptor instead.
func (*UserReply) Descriptor() ([]byte, []int) {
	return file_kratos_api_user_service_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserReply) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_kratos_api_user_service_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_kratos_api_user_service_v1_user_proto_rawDescGZIP(), []int{5}
}

type ListUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserReply           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReply) Reset() {
	*x = ListUsersReply{}
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReply) ProtoMessage() {}

func (x *ListUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_user_service_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReply.ProtoReflect.Descriptor instead.
func (*ListUsersReply) Descriptor() ([]byte, []int) {
	return file_kratos_api_user_service_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersReply) GetUsers() []*UserReply {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_kratos_api_user_service_v1_user_proto protoreflect.FileDescriptor

const file_kratos_api_user_service_v1_user_proto_rawDesc = "" +
	"\n" +
	"%kratos/api/user/service/v1/user.proto\x12\x0fuser.service.v1\x1a\x1cgoogle/api/annotations.proto\"q\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\"g\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\"\x1d\n" +
	"\vUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"_\n" +
	"\tUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\"'\n" +
	"\vDeleteReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10ListUsersRequest\"B\n" +
	"\x0eListUsersReply\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.user.service.v1.UserReplyR\x05users2\x82\x04\n" +
	"\vUserService\x12g\n" +
	"\bRegister\x12 .user.service.v1.RegisterRequest\x1a\x1a.user.service.v1.UserReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/users/register\x12[\n" +
	"\aGetUser\x12\x1c.user.service.v1.UserRequest\x1a\x1a.user.service.v1.UserReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/users/{id}\x12g\n" +
	"\n" +
	"UpdateUser\x12\".user.service.v1.UpdateUserRequest\x1a\x1a.user.service.v1.UserReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/users/{id}\x12`\n" +
	"\n" +
	"DeleteUser\x12\x1c.user.service.v1.UserRequest\x1a\x1c.user.service.v1.DeleteReply\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/users/{id}\x12b\n" +
	"\tListUsers\x12!.user.service.v1.ListUsersRequest\x1a\x1f.user.service.v1.ListUsersReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/usersB\x1fZ\x1dkratos/api/user/service/v1;v1b\x06proto3"

var (
	file_kratos_api_user_service_v1_user_proto_rawDescOnce sync.Once
	file_kratos_api_user_service_v1_user_proto_rawDescData []byte
)

func file_kratos_api_user_service_v1_user_proto_rawDescGZIP() []byte {
	file_kratos_api_user_service_v1_user_proto_rawDescOnce.Do(func() {
		file_kratos_api_user_service_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kratos_api_user_service_v1_user_proto_rawDesc), len(file_kratos_api_user_service_v1_user_proto_rawDesc)))
	})
	return file_kratos_api_user_service_v1_user_proto_rawDescData
}

var file_kratos_api_user_service_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kratos_api_user_service_v1_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: user.service.v1.RegisterRequest
	(*UpdateUserRequest)(nil), // 1: user.service.v1.UpdateUserRequest
	(*UserRequest)(nil),       // 2: user.service.v1.UserRequest
	(*UserReply)(nil),         // 3: user.service.v1.UserReply
	(*DeleteReply)(nil),       // 4: user.service.v1.DeleteReply
	(*ListUsersRequest)(nil),  // 5: user.service.v1.ListUsersRequest
	(*ListUsersReply)(nil),    // 6: user.service.v1.ListUsersReply
}
var file_kratos_api_user_service_v1_user_proto_depIdxs = []int32{
	3, // 0: user.service.v1.ListUsersReply.users:type_name -> user.service.v1.UserReply
	0, // 1: user.service.v1.UserService.Register:input_type -> user.service.v1.RegisterRequest
	2, // 2: user.service.v1.UserService.GetUser:input_type -> user.service.v1.UserRequest
	1, // 3: user.service.v1.UserService.UpdateUser:input_type -> user.service.v1.UpdateUserRequest
	2, // 4: user.service.v1.UserService.DeleteUser:input_type -> user.service.v1.UserRequest
	5, // 5: user.service.v1.UserService.ListUsers:input_type -> user.service.v1.ListUsersRequest
	3, // 6: user.service.v1.UserService.Register:output_type -> user.service.v1.UserReply
	3, // 7: user.service.v1.UserService.GetUser:output_type -> user.service.v1.UserReply
	3, // 8: user.service.v1.UserService.UpdateUser:output_type -> user.service.v1.UserReply
	4, // 9: user.service.v1.UserService.DeleteUser:output_type -> user.service.v1.DeleteReply
	6, // 10: user.service.v1.UserService.ListUsers:output_type -> user.service.v1.ListUsersReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kratos_api_user_service_v1_user_proto_init() }
func file_kratos_api_user_service_v1_user_proto_init() {
	if File_kratos_api_user_service_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kratos_api_user_service_v1_user_proto_rawDesc), len(file_kratos_api_user_service_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kratos_api_user_service_v1_user_proto_goTypes,
		DependencyIndexes: file_kratos_api_user_service_v1_user_proto_depIdxs,
		MessageInfos:      file_kratos_api_user_service_v1_user_proto_msgTypes,
	}.Build()
	File_kratos_api_user_service_v1_user_proto = out.File
	file_kratos_api_user_service_v1_user_proto_goTypes = nil
	file_kratos_api_user_service_v1_user_proto_depIdxs = nil
}
