// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-kratos/kratos/v2/internal/app"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"log"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all its dependencies
func InitializeApp(logger *log.Logger) (*app.App, error) {
	v := ProvideGRPCServerOptions()
	server := grpc.NewServer(v...)
	v2 := ProvideHTTPServerOptions()
	httpServer := http.NewServer(v2...)
	appApp := app.NewApp(server, httpServer, logger)
	return appApp, nil
}

// wire.go:

// ProvideGRPCServerOptions provides the default gRPC server options
func ProvideGRPCServerOptions() []grpc.ServerOption {
	return []grpc.ServerOption{grpc.Address(":52937")}
}

// ProvideHTTPServerOptions provides the default HTTP server options
func ProvideHTTPServerOptions() []http.ServerOption {
	return []http.ServerOption{http.Address(":52938")}
}
