// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: kratos/api/product/service/v1/product.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_kratos_api_product_service_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_kratos_api_product_service_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProductRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_kratos_api_product_service_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	UserId        int32                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductReply) Reset() {
	*x = ProductReply{}
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductReply) ProtoMessage() {}

func (x *ProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductReply.ProtoReflect.Descriptor instead.
func (*ProductReply) Descriptor() ([]byte, []int) {
	return file_kratos_api_product_service_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductReply) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ProductReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductReply) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_kratos_api_product_service_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserProductListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProductListRequest) Reset() {
	*x = UserProductListRequest{}
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProductListRequest) ProtoMessage() {}

func (x *UserProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProductListRequest.ProtoReflect.Descriptor instead.
func (*UserProductListRequest) Descriptor() ([]byte, []int) {
	return file_kratos_api_product_service_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *UserProductListRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserProductListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductReply        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProductListReply) Reset() {
	*x = UserProductListReply{}
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProductListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProductListReply) ProtoMessage() {}

func (x *UserProductListReply) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_api_product_service_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProductListReply.ProtoReflect.Descriptor instead.
func (*UserProductListReply) Descriptor() ([]byte, []int) {
	return file_kratos_api_product_service_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *UserProductListReply) GetProducts() []*ProductReply {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_kratos_api_product_service_v1_product_proto protoreflect.FileDescriptor

const file_kratos_api_product_service_v1_product_proto_rawDesc = "" +
	"\n" +
	"+kratos/api/product/service/v1/product.proto\x12\x12product.service.v1\x1a\x1cgoogle/api/annotations.proto\"{\n" +
	"\x14CreateProductRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x8b\x01\n" +
	"\x14UpdateProductRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"9\n" +
	"\x0eProductRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"\x83\x01\n" +
	"\fProductReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x05R\x06userId\"'\n" +
	"\vDeleteReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x16UserProductListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"T\n" +
	"\x14UserProductListReply\x12<\n" +
	"\bproducts\x18\x01 \x03(\v2 .product.service.v1.ProductReplyR\bproducts2\xb4\x05\n" +
	"\x0eProductService\x12\x84\x01\n" +
	"\rCreateProduct\x12(.product.service.v1.CreateProductRequest\x1a .product.service.v1.ProductReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/users/{user_id}/products\x12}\n" +
	"\n" +
	"GetProduct\x12\".product.service.v1.ProductRequest\x1a .product.service.v1.ProductReply\")\x82\xd3\xe4\x93\x02#\x12!/v1/users/{user_id}/products/{id}\x12\x89\x01\n" +
	"\rUpdateProduct\x12(.product.service.v1.UpdateProductRequest\x1a .product.service.v1.ProductReply\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/v1/users/{user_id}/products/{id}\x12\x7f\n" +
	"\rDeleteProduct\x12\".product.service.v1.ProductRequest\x1a\x1f.product.service.v1.DeleteReply\")\x82\xd3\xe4\x93\x02#*!/v1/users/{user_id}/products/{id}\x12\x8e\x01\n" +
	"\x10ListUserProducts\x12*.product.service.v1.UserProductListRequest\x1a(.product.service.v1.UserProductListReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/users/{user_id}/productsB\"Z kratos/api/product/service/v1;v1b\x06proto3"

var (
	file_kratos_api_product_service_v1_product_proto_rawDescOnce sync.Once
	file_kratos_api_product_service_v1_product_proto_rawDescData []byte
)

func file_kratos_api_product_service_v1_product_proto_rawDescGZIP() []byte {
	file_kratos_api_product_service_v1_product_proto_rawDescOnce.Do(func() {
		file_kratos_api_product_service_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kratos_api_product_service_v1_product_proto_rawDesc), len(file_kratos_api_product_service_v1_product_proto_rawDesc)))
	})
	return file_kratos_api_product_service_v1_product_proto_rawDescData
}

var file_kratos_api_product_service_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kratos_api_product_service_v1_product_proto_goTypes = []any{
	(*CreateProductRequest)(nil),   // 0: product.service.v1.CreateProductRequest
	(*UpdateProductRequest)(nil),   // 1: product.service.v1.UpdateProductRequest
	(*ProductRequest)(nil),         // 2: product.service.v1.ProductRequest
	(*ProductReply)(nil),           // 3: product.service.v1.ProductReply
	(*DeleteReply)(nil),            // 4: product.service.v1.DeleteReply
	(*UserProductListRequest)(nil), // 5: product.service.v1.UserProductListRequest
	(*UserProductListReply)(nil),   // 6: product.service.v1.UserProductListReply
}
var file_kratos_api_product_service_v1_product_proto_depIdxs = []int32{
	3, // 0: product.service.v1.UserProductListReply.products:type_name -> product.service.v1.ProductReply
	0, // 1: product.service.v1.ProductService.CreateProduct:input_type -> product.service.v1.CreateProductRequest
	2, // 2: product.service.v1.ProductService.GetProduct:input_type -> product.service.v1.ProductRequest
	1, // 3: product.service.v1.ProductService.UpdateProduct:input_type -> product.service.v1.UpdateProductRequest
	2, // 4: product.service.v1.ProductService.DeleteProduct:input_type -> product.service.v1.ProductRequest
	5, // 5: product.service.v1.ProductService.ListUserProducts:input_type -> product.service.v1.UserProductListRequest
	3, // 6: product.service.v1.ProductService.CreateProduct:output_type -> product.service.v1.ProductReply
	3, // 7: product.service.v1.ProductService.GetProduct:output_type -> product.service.v1.ProductReply
	3, // 8: product.service.v1.ProductService.UpdateProduct:output_type -> product.service.v1.ProductReply
	4, // 9: product.service.v1.ProductService.DeleteProduct:output_type -> product.service.v1.DeleteReply
	6, // 10: product.service.v1.ProductService.ListUserProducts:output_type -> product.service.v1.UserProductListReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kratos_api_product_service_v1_product_proto_init() }
func file_kratos_api_product_service_v1_product_proto_init() {
	if File_kratos_api_product_service_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kratos_api_product_service_v1_product_proto_rawDesc), len(file_kratos_api_product_service_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kratos_api_product_service_v1_product_proto_goTypes,
		DependencyIndexes: file_kratos_api_product_service_v1_product_proto_depIdxs,
		MessageInfos:      file_kratos_api_product_service_v1_product_proto_msgTypes,
	}.Build()
	File_kratos_api_product_service_v1_product_proto = out.File
	file_kratos_api_product_service_v1_product_proto_goTypes = nil
	file_kratos_api_product_service_v1_product_proto_depIdxs = nil
}
